export { default as ArrowRight24 } from '@carbon/icons-vue/es/arrow--right/24';
export { default as Asleep24 } from '@carbon/icons-vue/es/asleep/24';
export { default as Awake24 } from '@carbon/icons-vue/es/awake/24';
export { default as CheckmarkOutline24 } from '@carbon/icons-vue/es/checkmark--outline/24';
export { default as Delete24 } from '@carbon/icons-vue/es/delete/24';
export { default as Events24 } from '@carbon/icons-vue/es/events/24';
export { default as Identification24 } from '@carbon/icons-vue/es/identification/24';
export { default as Settings24 } from '@carbon/icons-vue/es/settings/24';
export { default as UserAvatar24 } from '@carbon/icons-vue/es/user--avatar/24';
